global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hardlock-identity'
    static_configs:
      - targets: ['identity-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-encryption'
    static_configs:
      - targets: ['encryption-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-storage'
    static_configs:
      - targets: ['storage-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-access-control'
    static_configs:
      - targets: ['access-control-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-cold-wallet'
    static_configs:
      - targets: ['cold-wallet-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-audit'
    static_configs:
      - targets: ['audit-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-notification'
    static_configs:
      - targets: ['notification-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hardlock-gateway'
    static_configs:
      - targets: ['gateway:80']
    metrics_path: '/metrics'
    scrape_interval: 10s 